title: Das kleine Atelier
description: Kreativ-Atelier f체r Kinder (6-9 Jahre) daskleineatelierwien@gmail.com N채chster Termin am 5.6.2023, 15-17 Uhr, Ort wird noch bekannt gegeben WIR SIND Anna Lisa Kopeinig, MA, 35, P채dagogin mit Master in Sozialwissenschaften und MMag. art. Hannah Winkelbauer, 35, Bildende K체nstlerin, ehemals Journalistin und Mutter zweier Kinder.



remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
